runtime: python37
entrypoint: gunicorn -b :$PORT ingestapp:app
service: flights

#[START env]
env_variables:
  CLOUD_STORAGE_BUCKET: data_science_on_gcp_bucket
#[END env]


handlers:
- url: /.*
  script: ingestapp.app
